# Generated by Django 4.1.4 on 2022-12-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='CHAT ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_telegram',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID телеграмм пользователя'),
        ),
    ]
