# Generated by Django 4.1.4 on 2022-12-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'verbose_name': 'Пост пользователя', 'verbose_name_plural': 'Посты пользователей'},
        ),
    ]
