# Generated by Django 4.1.4 on 2022-12-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_userpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
