# Generated by Django 4.1.4 on 2023-01-01 10:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_userpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='post_images/', verbose_name='Фотография проекта'),
        ),
    ]
